version: 2
models:
  - name: stg_product
    description: "product table from adventureworks"
    columns:
      - name: product_id
        description: Product ID
        tests:
          - unique
          - not_null